In [1]:
import mxnet as mx
mx.__version__

'0.10.0'

In [2]:
a = mx.nd.array([[1,2,3], [4,5,6]])
a.size

6

In [3]:
a.shape

(2, 3)

In [4]:
a.dtype

numpy.float32

In [5]:
import numpy as np

b = mx.nd.array([[1,2,3], [2,3,4]], dtype=np.int32)
b.dtype

numpy.int32

In [6]:
b.asnumpy()

array([[1, 2, 3],
       [2, 3, 4]], dtype=int32)

In [7]:
a = mx.nd.array([[1,2,3], [4,5,6]])
b = a*a
b.asnumpy()

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]], dtype=float32)

In [8]:
a = mx.nd.array([[1,2,3], [4,5,6]])
print(a.shape)
print(a.asnumpy())

(2, 3)
[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [9]:
b = a.T
print(b.shape)
print(b.asnumpy())

(3, 2)
[[ 1.  4.]
 [ 2.  5.]
 [ 3.  6.]]


In [10]:
c = mx.nd.dot(a,b)
print(c.shape)
print(c.asnumpy())

(2, 2)
[[ 14.  32.]
 [ 32.  77.]]


In [12]:
c = mx.nd.uniform(low=0, high=1, shape=(1000,1000), ctx="cpu(0)")
d = mx.nd.normal(loc=1, scale=2, shape=(1000,1000), ctx="cpu(0)")
e = mx.nd.dot(c,d)
print(e.asnumpy()[:10])

[[ 450.05123901  453.43884277  443.54043579 ...,  452.92120361
   506.54067993  516.74542236]
 [ 465.80450439  464.30477905  489.93243408 ...,  504.17578125
   519.97106934  526.63946533]
 [ 483.8293457   444.73861694  482.64266968 ...,  432.90298462
   513.12689209  528.28619385]
 ..., 
 [ 474.87454224  441.7286377   468.60150146 ...,  446.21191406  524.909729
   482.4437561 ]
 [ 469.67263794  430.80844116  492.58398438 ...,  486.33465576
   494.58984375  515.58190918]
 [ 491.54232788  490.42538452  513.85015869 ...,  449.76693726  518.78125
   518.44592285]]
